name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: "20.47.72.6"
          username: "azureuser"
          key: ${{ secrets.VM_SSH_KEY }}
          source: "."
          target: "/home/azureuser/site"

      - name: Deploy to Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "20.47.72.6"
          username: "azureuser"
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            sudo mkdir -p /var/www/html
            sudo cp -r /home/azureuser/site/* /var/www/html/
            sudo systemctl restart nginx
